
[font]
size = 12.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control|Shift"

[terminal.shell]
program = "/usr/bin/bash"

[window]
decorations = "None"
opacity = 0.95
